"""Fractions question bank, keyed by NCERT section code.

Fields per question: difficulty, question_type, concept, question_text,
options ([] for NUMERICAL), correct_answer, explanation.
topic / learning_objective are inherited from the section at seed time.
"""


def _q(difficulty, question_type, concept, text, options, answer, explanation):
    return {
        "difficulty": difficulty,
        "question_type": question_type,
        "concept": concept,
        "question_text": text,
        "options": options,
        "correct_answer": answer,
        "explanation": explanation,
        "marks": 1,
    }


FRACTIONS_QUESTIONS = {
    "7.1": [
        _q("EASY", "MCQ", "Equal sharing",
           "4 friends share 1 roti equally. What fraction of the roti does each friend get?",
           ["1/2", "1/3", "1/4", "1/5"], "1/4",
           "Dividing 1 whole into 4 equal parts gives one-fourth (1/4) to each friend."),
        _q("EASY", "CONCEPTUAL", "Fractional unit",
           "Which statement correctly describes one-third of a whole?",
           ["The whole is divided into 3 equal parts and one part is taken",
            "The whole is divided into 3 parts of any size and one part is taken",
            "Three wholes are put together",
            "The whole is divided into 2 equal parts"],
           "The whole is divided into 3 equal parts and one part is taken",
           "A fractional unit always comes from EQUAL parts. One-third is one of 3 equal parts."),
        _q("EASY", "NUMERICAL", "Fractional unit",
           "A ribbon is folded into 8 equal parts. Each part is 1/? of the ribbon. Write the missing number.",
           [], "8",
           "8 equal parts means each part is one-eighth, 1/8."),
        _q("MEDIUM", "CONCEPTUAL", "Equal parts",
           "A square is cut into 4 pieces, but one piece is bigger than the others. Is each piece one-fourth of the square?",
           ["Yes, because there are 4 pieces",
            "No, because the pieces are not all equal",
            "Yes, because the pieces are parts of a square",
            "No, because 4 pieces make one-half"],
           "No, because the pieces are not all equal",
           "Fourths must be 4 EQUAL parts. Unequal pieces are not fourths."),
        _q("HARD", "NUMERICAL", "Sharing several wholes",
           "3 children share 2 equal chapatis equally. Each chapati is cut into 3 equal parts. How many parts does each child get?",
           [], "2",
           "2 chapatis give 6 parts. Shared by 3 children, each gets 6 / 3 = 2 parts, i.e. 2/3 of a chapati."),
    ],
    "7.2": [
        _q("EASY", "MCQ", "Fraction of a whole",
           "A pizza is cut into 8 equal slices and 3 slices are eaten. What fraction of the pizza is eaten?",
           ["3/5", "3/8", "8/3", "5/8"], "3/8",
           "3 of the 8 equal parts are eaten, so the fraction is 3/8."),
        _q("EASY", "NUMERICAL", "Denominator",
           "In the fraction 5/9, what is the denominator?",
           [], "9",
           "The denominator is the bottom number: the number of equal parts in the whole."),
        _q("MEDIUM", "MCQ", "Fraction of a whole",
           "A rectangle is divided into 6 equal parts and 4 parts are shaded. What fraction is NOT shaded?",
           ["4/6", "2/6", "2/4", "6/2"], "2/6",
           "6 - 4 = 2 parts are not shaded, so 2/6."),
        _q("MEDIUM", "CONCEPTUAL", "Denominator",
           "What does the denominator of a fraction tell us?",
           ["How many equal parts the whole is divided into",
            "How many parts are taken",
            "The length of the whole in cm",
            "Whether the fraction is greater than 1"],
           "How many equal parts the whole is divided into",
           "The denominator counts the equal parts in the whole; the numerator counts the parts taken."),
        _q("HARD", "NUMERICAL", "Parts of a whole",
           "A rope is cut into 10 equal pieces. Ravi takes 3 pieces and Meera takes 2 pieces. What fraction of the rope is left? Write it with denominator 10.",
           [], "5/10",
           "3 + 2 = 5 pieces are taken, so 10 - 5 = 5 pieces are left: 5/10."),
    ],
    "7.3": [
        _q("EASY", "MCQ", "Measuring with fractional units",
           "A string is measured using a stick that is 1/2 metre long. The string is exactly 5 such sticks long. How long is the string?",
           ["5/2 m", "2/5 m", "5 m", "10 m"], "5/2 m",
           "5 x 1/2 = 5/2 m, which is 2 and a half metres."),
        _q("EASY", "NUMERICAL", "Fractional units in a whole",
           "How many units of 1/4 make 1 whole?",
           [], "4",
           "Four quarters make one whole: 4 x 1/4 = 1."),
        _q("MEDIUM", "MCQ", "Measuring capacity",
           "A jug is filled by pouring a 1/4-litre cup 9 times. How many litres does the jug hold?",
           ["9/4 litres", "4/9 litres", "13/4 litres", "9 litres"], "9/4 litres",
           "9 x 1/4 = 9/4 litres (2 and 1/4 litres)."),
        _q("MEDIUM", "CONCEPTUAL", "Need for fractional units",
           "A table is a little longer than 2 sticks of 1 metre each. Why do we need fractional units to measure it?",
           ["Whole-number units cannot measure the leftover part exactly",
            "Fractions are always bigger than whole numbers",
            "Tables can only be measured in fractions",
            "A stick cannot be used more than once"],
           "Whole-number units cannot measure the leftover part exactly",
           "The leftover length is less than one whole unit, so a smaller fractional unit is needed."),
        _q("HARD", "NUMERICAL", "Measuring with fractional units",
           "A ribbon is 11 units of 1/4 m long. How many whole metres does it fully cover?",
           [], "2",
           "11 x 1/4 = 11/4 m = 2 and 3/4 m, so it fully covers 2 whole metres."),
    ],
    "7.4": [
        _q("EASY", "MCQ", "Number line",
           "To mark 1/4 on a number line, into how many equal parts do we divide the segment from 0 to 1?",
           ["2", "3", "4", "5"], "4",
           "The denominator 4 tells us to make 4 equal parts."),
        _q("EASY", "NUMERICAL", "Number line",
           "The segment from 0 to 1 is divided into 5 equal parts. Which fraction is at the 3rd mark from 0?",
           [], "3/5",
           "The 3rd mark of 5 equal parts is 3/5."),
        _q("MEDIUM", "MCQ", "Number line",
           "Which fraction lies exactly halfway between 0 and 1 on the number line?",
           ["1/4", "1/2", "2/3", "3/4"], "1/2",
           "Halfway between 0 and 1 is one-half."),
        _q("MEDIUM", "CONCEPTUAL", "Fractions greater than 1",
           "Where does the fraction 5/4 lie on the number line?",
           ["Between 1 and 2", "Between 0 and 1", "Exactly at 2", "Between 2 and 3"],
           "Between 1 and 2",
           "5/4 = 1 and 1/4, so it is a little to the right of 1."),
        _q("HARD", "NUMERICAL", "Number line",
           "Each unit interval on a number line is divided into 6 equal parts. Starting from 0, which fraction is at the 11th mark?",
           [], "11/6",
           "Each mark is 1/6, so the 11th mark is 11/6 (between 1 and 2)."),
    ],
    "7.5": [
        _q("EASY", "MCQ", "Mixed fractions",
           "Which of these is a mixed fraction?",
           ["2 1/3", "7/3", "1/3", "3/3"], "2 1/3",
           "A mixed fraction has a whole-number part and a fraction part: 2 and 1/3."),
        _q("EASY", "NUMERICAL", "Improper to mixed",
           "Write 7/4 as a mixed fraction. What is the whole-number part?",
           [], "1",
           "7 / 4 = 1 remainder 3, so 7/4 = 1 3/4. The whole part is 1."),
        _q("MEDIUM", "MCQ", "Mixed to improper",
           "Write 2 3/5 as an improper fraction.",
           ["13/5", "6/5", "11/5", "10/3"], "13/5",
           "(2 x 5 + 3)/5 = 13/5."),
        _q("MEDIUM", "CONCEPTUAL", "Improper fractions",
           "Which statement about improper fractions is correct?",
           ["The numerator is greater than or equal to the denominator",
            "The numerator is always less than the denominator",
            "The denominator is always 1",
            "They cannot be shown on a number line"],
           "The numerator is greater than or equal to the denominator",
           "Improper fractions such as 11/4 are at least 1 and can be marked on the number line."),
        _q("HARD", "NUMERICAL", "Improper to mixed",
           "Convert 23/6 to a mixed fraction. What is the numerator of the fraction part?",
           [], "5",
           "23 / 6 = 3 remainder 5, so 23/6 = 3 5/6. The numerator of the fraction part is 5."),
    ],
    "7.6": [
        _q("EASY", "MCQ", "Equivalent fractions",
           "Which fraction is equivalent to 1/2?",
           ["2/4", "2/3", "1/4", "3/5"], "2/4",
           "Multiply numerator and denominator of 1/2 by 2 to get 2/4."),
        _q("EASY", "NUMERICAL", "Equivalent fractions",
           "Fill in the blank: 2/3 = ?/12",
           [], "8",
           "3 x 4 = 12, so multiply the numerator by 4 too: 2 x 4 = 8."),
        _q("MEDIUM", "MCQ", "Equivalent fractions",
           "Which pair of fractions is equivalent?",
           ["3/4 and 9/12", "2/5 and 4/15", "1/3 and 2/5", "5/6 and 10/11"],
           "3/4 and 9/12",
           "3/4 = (3 x 3)/(4 x 3) = 9/12."),
        _q("MEDIUM", "NUMERICAL", "Simplest form",
           "Write 12/18 in simplest form.",
           [], "2/3",
           "Divide numerator and denominator by 6: 12/18 = 2/3."),
        _q("MEDIUM", "CONCEPTUAL", "Why equivalence works",
           "Why does multiplying the numerator and denominator by the same non-zero number give an equivalent fraction?",
           ["Each equal part is split into smaller equal parts, so the same amount of the whole is shown",
            "The fraction becomes bigger",
            "The denominator is ignored",
            "The fraction always becomes a whole number"],
           "Each equal part is split into smaller equal parts, so the same amount of the whole is shown",
           "Splitting every part into the same number of smaller parts changes the count but not the amount."),
        _q("HARD", "NUMERICAL", "Equivalent fractions",
           "If 5/8 = x/40, find x.",
           [], "25",
           "8 x 5 = 40, so x = 5 x 5 = 25."),
    ],
    "7.7": [
        _q("EASY", "MCQ", "Comparing like fractions",
           "Which is greater: 3/7 or 5/7?",
           ["3/7", "5/7", "They are equal", "Cannot say"], "5/7",
           "The denominators are the same, so the larger numerator gives the larger fraction."),
        _q("EASY", "CONCEPTUAL", "Same numerator",
           "When two fractions have the same numerator, the fraction with the ____ denominator is greater.",
           ["smaller", "larger", "odd", "even"], "smaller",
           "A smaller denominator means fewer, bigger parts, e.g. 1/3 > 1/5."),
        _q("MEDIUM", "MCQ", "Comparing unlike fractions",
           "Which comparison is correct?",
           ["2/3 > 3/5", "2/3 < 3/5", "2/3 = 3/5", "They cannot be compared"],
           "2/3 > 3/5",
           "2/3 = 10/15 and 3/5 = 9/15, and 10/15 > 9/15."),
        _q("MEDIUM", "NUMERICAL", "Finding the greatest",
           "Which is the greatest of 1/2, 3/4 and 5/8? Write the fraction.",
           [], "3/4",
           "With denominator 8: 4/8, 6/8, 5/8. The largest is 6/8 = 3/4."),
        _q("HARD", "MCQ", "Ordering fractions",
           "Arrange in ascending order: 1/2, 2/3, 3/8.",
           ["3/8, 1/2, 2/3", "1/2, 3/8, 2/3", "2/3, 1/2, 3/8", "3/8, 2/3, 1/2"],
           "3/8, 1/2, 2/3",
           "With denominator 24: 12/24, 16/24, 9/24. Ascending: 9/24, 12/24, 16/24 = 3/8, 1/2, 2/3."),
        _q("HARD", "CONCEPTUAL", "Comparing in context",
           "Anu ate 3/5 of a roti and Raju ate 4/7 of an identical roti. Who ate more?",
           ["Anu, because 3/5 > 4/7",
            "Raju, because 7 is greater than 5",
            "Raju, because 4 is greater than 3",
            "Both ate the same amount"],
           "Anu, because 3/5 > 4/7",
           "With denominator 35: 3/5 = 21/35 and 4/7 = 20/35, so Anu ate more. Comparing numerators or denominators alone is misleading."),
    ],
    "7.8": [
        _q("EASY", "MCQ", "Adding like fractions",
           "Find 3/8 + 2/8.",
           ["5/8", "5/16", "6/8", "1/8"], "5/8",
           "Same denominator: add the numerators and keep the denominator. 3 + 2 = 5, so 5/8."),
        _q("EASY", "NUMERICAL", "Subtracting like fractions",
           "Find 8/11 - 3/11.",
           [], "5/11",
           "Subtract the numerators: 8 - 3 = 5. The denominator stays 11."),
        _q("MEDIUM", "MCQ", "Adding unlike fractions",
           "Find 1/2 + 1/4.",
           ["2/6", "3/4", "2/4", "1/6"], "3/4",
           "1/2 = 2/4, so 2/4 + 1/4 = 3/4."),
        _q("MEDIUM", "NUMERICAL", "Subtracting unlike fractions",
           "Find 3/4 - 1/8.",
           [], "5/8",
           "3/4 = 6/8, so 6/8 - 1/8 = 5/8."),
        _q("HARD", "CONCEPTUAL", "Common denominators",
           "Why is 1/3 + 1/4 NOT equal to 2/7?",
           ["The parts are of different sizes, so we must first use a common denominator",
            "Because 2/7 is less than 1",
            "Because fractions cannot be added",
            "Because 3 and 4 are different numbers"],
           "The parts are of different sizes, so we must first use a common denominator",
           "1/3 + 1/4 = 4/12 + 3/12 = 7/12. Denominators are never added."),
        _q("HARD", "NUMERICAL", "Word problem",
           "A jug holds 1 litre of water. Riya drinks 1/2 litre and Sam drinks 1/3 litre. How much water is left? Write it as a fraction of a litre.",
           [], "1/6",
           "1/2 + 1/3 = 3/6 + 2/6 = 5/6 drunk. 1 - 5/6 = 1/6 litre left."),
    ],
    "7.9": [
        _q("EASY", "CONCEPTUAL", "History of fractions",
           "Why did people in ancient civilisations need fractions?",
           ["To share, measure and divide things like grain and land that were not whole numbers",
            "Only to write poems",
            "To avoid using whole numbers",
            "They did not use fractions"],
           "To share, measure and divide things like grain and land that were not whole numbers",
           "Everyday sharing and measuring often gave amounts that were not whole numbers."),
        _q("EASY", "MCQ", "Unit fractions",
           "Which of these is a unit fraction?",
           ["1/7", "2/7", "7/2", "7/7"], "1/7",
           "A unit fraction has numerator 1."),
        _q("MEDIUM", "NUMERICAL", "Sum of unit fractions",
           "Egyptians often wrote fractions as sums of unit fractions. Fill in the blank: 3/4 = 1/2 + 1/?",
           [], "4",
           "3/4 - 1/2 = 3/4 - 2/4 = 1/4."),
    ],
}
